### ISSUE TITLE
login and other actions missing from footer on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#125]
<img width="642" alt="screen shot 2016-06-07 at 3 29 50 pm" src="https://cloud.githubusercontent.com/assets/263285/15873527/bf0148fa-2cc4-11e6-97db-285e8e076e42.png">

**Comment by cguardia** [comment]
This commit caused the links to disappear: https://github.com/isawnyu/isaw.web/commit/657df82ca669be7da4d6280eca9fffcf4fc399a0

What happened was that we switched to a "raw" mode for the replace rule, which caused the footer to be copied before the rule that added the links from the personal tools was executed.

I tried several ways to avoid the conflict in the rules, but was not successful, but since we control the viewlet for the footer, I added the actions there. 

This works and is committed to master, but I was not able to deploy. @alecpm could you deploy please?

**Comment by paregorios** [comment]
If we're confident that this won't have any knock-on effects elsewhere, yes please deploy to production. We have users blocked from login and complaining. Yes, we can give them work-arounds, but it will be a hard problem to contain.

**Comment by alecpm** [comment]
Deployed to production, along with all of @cewing's more recent fixes.

**Comment by paregorios** [comment]
Great!
