### ISSUE TITLE
Using "event listing" display style on a collection ignores the filters

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#175]
After creating a collection that searches for all events in a particular date range that have certain text in the title, I tried switching the display style to "Event Listing". This caused the collection to display all future events, rather than just the collection results.

https://isaw.nyu.edu/exhibitions/time-cosmos/tc-events/

**Comment by paregorios** [comment]
@cguardia and/or @alecpm : I assume this is because grabbing event items from /events is hardwired into the events view template. How hard would it be to make this look only at the folder or collection where it's applied as @k2soule describes? 

Reason: We had hoped to feature exhibition-related events in a separate location under /exhibitions (even though they event items themselves are in /events and are showing up on the isaw-wide events calendar, which we also want). I.e., we want to author events in one place (/events), but use them (filtered through collections) elsewhere on the site.

**Comment by alecpm** [comment]
It shouldn't be too hard to switch the event listing logic to use the collection query if it's a collection. The pagination stuff might be a little tricky, but I don't expect it would take more than a couple hours.

**Comment by paregorios** [comment]
@alecpm thanks ... at a "couple of hours" it sounds to me like this is a candidate for a story on next iteration, rather than a "quick fix" sort of item. Would you concur?

**Comment by alecpm** [comment]
Yeah, it's a small story or a big ticket.

**Comment by alecpm** [comment]
One question on this. We have a search filter on the event listing page. If the "Search all" radio button is selected, should the search override any "Event start" date filter alreadt in the collection to show events from all time which otherwise match the collection criteria, or should the search remain limited to the Collection results when if those results have an "Event start" restriction built into the collection criteria?

**Comment by alecpm** [comment]
This is deployed to staging, for now I am overriding any Collection "Event start" criteria when "Search all" is used, but it will be easy to do otherwise if desired.

**Comment by paregorios** [comment]
Please deploy to production.

**Comment by alecpm** [comment]
Deployed

**Comment by paregorios** [comment]
@k2soule please check on production and see if this looks good to you. If so, we can close the ticket.

**Comment by k2soule** [comment]
The collection is displaying tagged events correctly in event listing view now, but the date range is still being ignored. Since this is technically a separate issue, I've opened a new ticket or it. Closing this one.
