### ISSUE TITLE
set up a dev server in AWS for ISAW website: 13

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#292]
Including converting deployment process to Ansible.

**Comment by paregorios** [comment]
and ansiblize our deployment and test it

**Comment by alecpm** [comment]
For the purposes of development this is complete:

http://18.191.208.46/

The repo for the ansible config is here:

https://github.com/isawnyu/isaw-ansible/

It still needs SSL enabled, but we have another ticket for that. Additionally, the front end server should be switched to apache with SSO enabled, but that's not necessary for development (at least not initially) since the devs don't have NYU accounts.

**Comment by skleinfeldt** [comment]
@paregorios should we give it a name so it's easier to find? We could use isaw.jazkarta.com.

**Comment by paregorios** [comment]
fine by me

Tom Elliott, Ph.D.
Associate Director for Digital Programs
Senior Research Scholar
Institute for the Study of the Ancient World
New York University
tom.elliott@nyu.edu

http://isaw.nyu.edu/people/staff/tom-elliott
pronouns: he, him
OrcId: http://orcid.org/0000-0002-4114-6677

**Comment by skleinfeldt** [comment]
I think we need @cguardia to do this, right @alecpm? I'll make a new ticket for that so we don't forget. @paregorios you can close this one when you're satisfied.
