### ISSUE TITLE
don't reset image size in insert/edit image dialog: 13

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#319]
When editing an existing image that's already been embedded, the image-size combo box resets to the "original" image size, such that when saving changes made in other fields it also changes any previously set image size.

**Comment by paregorios** [comment]
blocked by #321

**Comment by alecpm** [comment]
According to the change log the newly deployed TinyMCE (1.3.28) has a fix for this issue. Please test.

As a side note: for reasons I don't recall, we "upgraded" TinyMCE to 1.4.2 at some point, but that appears to have been a dead end version intended for eventual use with Plone 5 (where that add-on has been replaced entirely). The last release on the 1.4 series was 1.4.3 in June 2015, but it has been unmaintained since. The 1.3 series – which we are now back on – is still being updated, and version 1.3.28 was released in January 2018 and intended for inclusion with Plone 4.3.18.

**Comment by alecpm** [comment]
Looks like we've overridden the JS for every TinyMCE plugin for the alt text changes. We'll have to undo/redo that using the resources from the updated TinyMCE. Maybe this is a task best assigned to @cguardia who's familiar with the specific changes needed.

I suggest using a z3c.jbot override for each specific skin file that needs changes instead of pulling in the whole folder.

**Comment by cguardia** [comment]
I switched to z3c.jbot as suggested, then updated the js with the changes needed to preserve the selected scale. Still not deployed to staging.

**Comment by alecpm** [comment]
Should be merged and deployed to staging now.

**Comment by paregorios** [comment]
Works great! Please merge to master and deploy to production.
