### ISSUE TITLE
header layout problems with FF on Ubuntu: 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#323]
From @sjhuskey via email:

> While viewing the program at http://isaw.nyu.edu/events/datam-conference, I noticed that the layout of the header for the ISAW site is not being displayed as you might expect. I'm running Firefox on Ubuntu 16.04 LTS, so that might have something to do with it. I checked, and the problem does not exist when I view the page in Chrome.
>
> Anyway, I've attached a screen shot of the upper left corner of my screen. If I increase the `width` on `#portal-top h1 a` from 350px to 360px, the problem is resolved in Firefox. It does not affect how the page is rendered in Chrome.

![screenshot_2018-09-12 conference digital approaches to teaching the ancient mediterranean](https://user-images.githubusercontent.com/263285/45449778-b6ed6f00-b69b-11e8-9ed8-f2dbca55e5be.png)

**Comment by alecpm** [comment]
I suggest trying `box-sizing: border-box;`

**Comment by cguardia** [comment]
@alecpm's suggestion does not work. Will probably need to go with the original suggestion.

**Comment by alecpm** [comment]
Too bad. I did notice that we do have a some `box-sizing` related issues that have cropped up because of the bold new borders around images. See e.g. the right border being cut off on the floated image here:

http://isaw.nyu.edu/events/datam-conference

And the layout of the thumbnails here:

http://isaw.nyu.edu/exhibitions/catalogues/restoring-the-minoans-elizabeth-price-and-sir-arthur-evans

Adding `#content a img {box-sizing: border-box;}` fixes those issues. Additionally, I think we could use a `a.publication-images.link-overlay, a.publication-images.link-overlay:hover {text-decoration: none !important;}` to get rid of the weird line appearing with the thumbnail links.

**Comment by alecpm** [comment]
I think I've taken care of this as part of issues that cropped up on #364.

**Comment by paregorios** [comment]
Hi @sjhuskey! We think we've fixed this. Can you have a look at our staging server (link below) to see if the layout is fixed for you with Firefox on Ubuntu 16.04 LTS? Thanks!

**Comment by paregorios** [comment]
@sjkuskey the link is https://isaw.jazkarta.com/

**Comment by paregorios** [comment]
please merge to master and deploy to production

**Comment by sjhuskey** [comment]
Sorry to be late to the party. I just looked at it (now using Ubuntu 18.04.1). The issue has been fixed, as far as I can tell.
