### ISSUE TITLE
implement ansible for production: 8

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#356]
blocker for #318

**Comment by paregorios** [comment]
@alecpm what's our best approach to reviewing this ticket and its friend #318?

**Comment by alecpm** [comment]
The relevant changes are in one commit here:

https://github.com/isawnyu/isaw-ansible/commit/f4a3ff8ddc9a9eb76981d5ee9ee1ec007e40700a

It's probably a good idea for @jessesnyder or @cguardia to review those changes and ensure the playbook runs for them on staging (staging and production use the same playbook with minor configuration differences).

**Comment by paregorios** [comment]
We'll assign this during standup today.

**Comment by paregorios** [comment]
Assigning to @jessesnyder to review code as suggested by @alecpm above

**Comment by jessesnyder** [comment]
@alecpm Can you provide the command[s] you use to run the playbook for staging?

**Comment by alecpm** [comment]
```ansible-playbook -i inventory.cfg -l staging playbook.yml --vault-password vault-pass```

**Comment by paregorios** [comment]
Alec to run once against new VM.

**Comment by paregorios** [comment]
Blocked for availability of new VM.

**Comment by alecpm** [comment]
I've run into an issue with setting up the shibboleth SP on Ubuntu 18.04. I'm not sure we actually need this anymore though with the Plone based SP setup though. Apparently, the shibboleth packages in Ubuntu `universe` [have some strange dependency issues](https://shibboleth.1660669.n2.nabble.com/Install-Shibboleth-SP-with-libcurl4-td7639706.html)

I've worked around this by installing from the updated [SWITCH repo for shibboleth](http://pkg.switch.ch/switchaai/). This installs Shibboleth 3 instead of 2 though, and that upgrade may have consequences for the configuration. Again, it's not clear to me whether this is even needed with the new SAML setup.

**Comment by paregorios** [comment]
Noted in last night's error messaging from the new server:

> Subject: Cron <plone_daemon@new-isaw4> cd /usr/local/plone-4.3/primary && bin/backup && echo "backup""_success for primary"
> Date: Thu, 15 Aug 2019 02:30:01 -0400 (EDT)
> 
> /bin/sh: 1: bin/backup: not found
