### ISSUE TITLE
"sharing" tab changes have no effect on ISAW production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#397]
Steps to reproduce:

 - Login as an admin user to production and navigate to /people/staff
 - View the "sharing" tab
 - Un-click all the checkboxes for the user Josiah Carrberry
 - Click the "save" button

The page reloads. All content is missing from the table on the "sharing" tab.

Shift-reload the page. Everything is back, including the check-marks next to Josiah Carrberry. 

Blocker for troubleshooting #396, which is also urgent.

**Comment by alecpm** [comment]
This isn't a caching issue, but it's something we saw elsewhere on the site. It's making an AJAX `POST` request to `/@@updateSharingInfo` with the changes, but it should be a `POST` to `/people/staff/@@updateSharingInfo`. It's related to missing data about the current url in a Javascript context. I think it should be an easy fix.

If you need to make changes via this form before I manage to get a fix in place, you can disable javascript before loading the sharing tab and managing the settings. I have no idea why this form decided it needed to use fancy AJAX APIs to do the thing that the form does just fine on its own, but that's the underlying cause here.

**Comment by alecpm** [comment]
Good old `kss-bbb.js`

**Comment by alecpm** [comment]
We saw this same issue on DOaks after a Plone upgrade I think. The fix is a small change to the theme rules file which should be up on staging in a few minutes.

**Comment by alecpm** [comment]
It appears to be working well on staging. This is a very low impact change, so I will deploy to production for review and to enable work on #396.

**Comment by alecpm** [comment]
It should be working on production now.

**Comment by paregorios** [comment]
This is working. Thanks.
