### ISSUE TITLE
"folder lead image view" is busted: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#406]
Lead images are not properly displayed in the 'folder lead image view':

![Screen Shot 2019-09-30 at 2 35 53 PM](https://user-images.githubusercontent.com/263285/65910221-e39c2380-e38f-11e9-9b3f-cb79735996d1.png)

We would prefer a layout in which the images actually work, and are left-aligned. Like this manually created page:

![Screen Shot 2019-09-30 at 2 36 54 PM](https://user-images.githubusercontent.com/263285/65910338-180fdf80-e390-11e9-99ac-0590ea8346e6.png)

The "read more" links are really not necessary either.

**Comment by alecpm** [comment]
This is up on staging for review:

https://isaw.jazkarta.com/research/projects/

**Comment by paregorios** [comment]
@alecpm Much improved! Any chance it would be easy to lose the "read more" links entirely?

**Comment by alecpm** [comment]
@paregorios sure, doing that via CSS is easiest, if that's acceptable. Since it's part of the original template in collective.contentleadimage customizing that template isn't ideal. We have already customized that package to improve alt text support (which was the source of the bug with the missing images in the listing to begin with), so it's not out of the question to remove it from the template.

**Comment by paregorios** [comment]
@alecpm CSS sounds fine to me

**Comment by alecpm** [comment]
OK, you it should be hidden once you reload.

**Comment by paregorios** [comment]
Looks great. Let's merge and deploy to production.
