### ISSUE TITLE
fix up the "related items" portlet: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#444]
There are some deficiencies in the current state of the "related items" portlet as it appears on the ISAW website. We need the following things fixed ([see example at bottom of page here](https://isaw.nyu.edu/skunkworks/portlet-experiments/page)).

## Portlet title customization doesn't work

Changing the portlet title like this:

![Screen Shot 2022-11-04 at 4 05 47 PM](https://user-images.githubusercontent.com/263285/200074794-3e21df72-a696-447c-a2c7-c5fa64414fdc.png)

Makes no change in what we see on the page:

![Screen Shot 2022-11-04 at 4 06 53 PM](https://user-images.githubusercontent.com/263285/200074872-000de883-ba23-4ebd-9ab2-c4f2f951e4a6.png)

## Descriptions of related items not shown in portlet

Even if we select "display description" in the portlet config:

![Screen Shot 2022-11-04 at 4 13 35 PM](https://user-images.githubusercontent.com/263285/200075820-04df2e8b-9e3b-487e-9e16-99e625d1f280.png)

And we ensure that the relevant content items have descriptions:

![Screen Shot 2022-11-04 at 4 12 06 PM](https://user-images.githubusercontent.com/263285/200075908-f5b6bdf8-1d18-46ff-aa22-4741f1f1fcbb.png)

We just see whitespace in the portlet (see screen capture above)

## The actual HTML generated for the portlet presents problems for accessibility and CSS application:

```html
<div class="relatedItems">
    <div class="visualClear" id="clear-space-before-relatedItemBox"><!-- --></div>
    <dl id="relatedItemBox">
        <dt>Related content</dt>
            <dd>
                <span class="contenttype-file">
                    <a href="https://isaw.nyu.edu/guide/finance/forms-docs/miscellaneous-expenses-reimbursement-example/view" class="state-internal">Miscellaneous Expenses Reimbursement Example</a>
                </span>
            </dd>
            <dd>
                <span class="contenttype-file">
                    <a href="https://isaw.nyu.edu/guide/finance/forms-docs/commonly-used-account-codes-isaw/view" class="state-internal">Commonly Used Account Codes (ISAW)</a>
                </span>
            </dd>
            <dd>
                <span class="contenttype-file">
                    <a href="https://isaw.nyu.edu/guide/finance/forms-docs/operational-facility-account-codes-isaw/view" class="state-published">Operational &amp; Facility Account Codes (ISAW)</a>
                </span>
            </dd>
    </dl>
</div>
```

I think we'd rather see something like this:

```html
<div class="relatedItems">
    <div id="relatedItemBox">
        <h2 class="portletHeader">{Title from portlet config}</h2>
        <ul class="portletLinkList">
            <li class="portletItem ">
                <div>
                    <a class="contenttype-file itemTitle"
                        href="https://isaw.nyu.edu/guide/finance/forms-docs/miscellaneous-expenses-reimbursement-example/view">Miscellaneous
                        Expenses Reimbursement Example</a>
                    <span class="itemDescription">An example of how to request a reimbursement for miscellaneous
                        expenses.</span>
                </div>
            </li>
            <li>
                <div>
                    <a class="contenttype-file itemTitle"
                        href="https://isaw.nyu.edu/guide/finance/forms-docs/commonly-used-account-codes-isaw/view">Commonly
                        Used Account Codes (ISAW)</a>
                    <span class="itemDescription">lorem ipsum</span>
                </div>
            </li>
            <li>
                <div>
                    <a class="contenttype-file itemTitle"
                        href="https://isaw.nyu.edu/guide/finance/forms-docs/operational-facility-account-codes-isaw/view">Operational
                        &amp; Facility Account Codes (ISAW)</a>
                    <span class="itemDescription">lorem ipsum</span>
                </div>
            </li>
        </ul>
    </div>
</div>
```

**Comment by alecpm** [comment]
@paregorios so I think there's a little confusion here, the content under "Related Content" is coming from a default Plone viewlet that renders the related items.

The related items portlet isn't actually rendering on the page. That portlet comes from an add-on [collective.portlet.relateditems](https://pypi.org/project/collective.portlet.relateditems/), which doesn't really have much to do with "Related Items" (though there are circumstances where the related items are used to determine the keyword/text searches used to populate the portlet). It does a site search for content with similar tags. I've tweaked the configuration of that portlet so that it shows up on the page with some recent content. You should be able to see what it looks like, and that it does respect the title and description settings. However, I suspect you don't really want it unless you're making extensive use of tags.

I suggest we ignore the portlet for now and make some customizations to the related items viewlet template. We can't really make it configurable, but we can give it a better default rendering. Is there a title you'd prefer to use globally vs `related content`? Would you prefer if it always showed descriptions?

**Comment by paregorios** [comment]
@alecpm thanks for the clarifications! I think that, giving the use cases that are driving our work this week, the fixed-up collection portlet that you're working on in #445 is going to meet all our needs, and (frankly) with more flexibility. So I propose we drop this ticket from the current iteration and it can hang out on the backlog until/if we need it. What do you think?

**Comment by alecpm** [comment]
@paregorios Sounds good to me, let me know if you want me to hide that viewlet globally.
