### ISSUE TITLE
default workflow problems

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#48]
The following problems have been identified through manipulation of test users, groups, and content on production inside the ```/permission-tests/default-workflow-tests``` folder.

Settings via "Sharing" tab on the folder:
-------------------------------------------------------
![perms](https://cloud.githubusercontent.com/assets/263285/9429155/8f9c2146-498c-11e5-83a7-e06a9ce90db9.jpg)

A test user was created and added to each of the indicated groups and then various content items created and manipulated. The following deviations from expectations were noted. Can we adjust as indicated?

 1. A user in "Test Writers Group" can submit their own content for review. They cannot submit other user's content for review because they cannot even access it (they don't have "can view). Can they submit their own content items because the are the owners of them? Can we easily take away their ability to submit unless someone gives them "can edit"?

 2. A user in "Test Editors Group" can edit content that has been submitted for review. Is this standard?

 3. A user in "Test Publishers Group" cannot check in a submitted working copy that had been checked out by someone else (although a "Test Publishers Group" user can cancel a checkout). Can we adjust to enable users in groups with "can review" to check in working copies?

**Comment by skleinfeldt** [comment]
You'll probably want to verify during your meeting with those who have much greater knowledge that me, but:

Yes owners normally have god-like permissions on their own content, they can submit and edit even after submitted and *even* after published in the standard Plone workflow - whereas they can't even see others' draft content. These behaviors can be customized, as @alecpm wrote about on that other ticket, and I don't think this is particularly difficult, although IIRC you have to reindex everything to pick up the new permissions, which is time consuming.

I'm not so familiar with working copies, but I imagine the same thing applies, since it is built on the same foundational technology.

**Comment by paregorios** [comment]
See #45 for discussion of editors being able to submit. I think there may be some prior looseness of terminology on my part contributing to confusion here.

**Comment by paregorios** [comment]
NB: child folders do not properly acquire all possible states from the intranet workflow. See separate ticket: #42.

**Comment by alecpm** [comment]
1) I have limited the "Request Review" permission to Editors.  Content owners without the "can edit" role will not be able to submit content.

2) I have removed the edit permissions from the Editor role when in the pending state.

3) The global check in permission has been changed so that the Reviewer role can check in content.  However, the checkin views require the "Modify Portal Content" permission, so that only people with the edit permission can check in content.  I've created a custom version of those views which require only the check-in permission.

These changes are deployed to dev.  To deploy them to production, run the buildout, restart the instances, visit the Add-Ons control panel and run the isaw.policy upgrades.  To update permissions for existing content, you will need to visit /portal_workflow/updateRoleMappings and click the "Update security settings," which may take some time.

**Comment by paregorios** [comment]
Will test but blocked for resolution of latest problems with #40.

**Comment by paregorios** [comment]
Looks like the plones on dev are churning through the update permissions step; I'm going to have to wait to test in the hopes that finishes ... it's too slow and intermittent right now to be efficient.

**Comment by alecpm** [comment]
It looks to me like they've finished

**Comment by paregorios** [comment]
hmmm two plones are still pegged at around 100% each

**Comment by alecpm** [comment]
All three are pegged, but it does not appear to be due to workflow remapping, which completed some time ago AFAICT.

**Comment by paregorios** [comment]
As of this morning (Sunday) all 3 of the plones on staging are still pegged. I tailed the logs I could find in /srv/isaw.web./var/log and /var/log/apache but am not sure if anything there is causing it. 

I'm not comfortable deploying the changes we've made since design rollout to production until we can figured out and remedy what's causing this.

**Comment by alecpm** [comment]
I am perplexed about what could have caused the high CPU usage across all clients.  However, restarting the clients and zeoserver appears to have resolved the problem.
