### ISSUE TITLE
Establsh 5.1 test/migration server in AWS

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#531]
- [x] spec needs
- [x] instantiate ec2 instance
- [x] configure plone/ansible/etc.

**Comment by alecpm** [comment]
I would suggest using a t4g.medium server for the ISAW upgrade/staging server. This is an architecture switch from Intel XEON to ARM Graviton2, which should provide significantly better price/performance. For production we would likely upgrade that to t4g.large. If the new architecture turns out to be incompatible with some dependency (e.g. shibboleth libraries) we can switch back to t3 class instances.

The instance should use the official Ubuntu 22.04 (Jammy LTS) AMI for ARM64 [ami-070f589e4b4a3fece](https://console.aws.amazon.com/ec2/home?region=us-east-1#launchAmi=ami-070f589e4b4a3fece). We cannot use the latest Ubuntu LTS, 24.04 Noble, because the migration requires both Python 2.7 and Python 3.8, and Noble provides only Python 3.12.

We will need approximately 250GB of storage on the primary SSD disk, which should be the `gp3` type.
