### ISSUE TITLE
add support for internal aliases (was "link items")

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#57]
When creating an html link inside content body, we have the option of either an internal or external link, and the internal link browser lets an editor choose an existing content item. Why isn't the internal item browser an option for creating a Link item? It's problematic to use typed-out URLs for such links.

**Comment by skleinfeldt** [comment]
Link content items are primarily for external links. If you want a certain site URL to redirect to another place, it is better to use the Aliases tab in the green bar on the existing item you want to redirect to. (I'm assuming we installed that tool, we usually do.)

Of course you still need to type out a URL with that tool, but I think that's a better way to do it since you don't have an extraneous content item. @alecpm correct me if I'm wrong.

**Comment by k2soule** [comment]
I don't see an Aliases tab, so I don' t know whether that's an option.
Here is an example of what I'm trying to accomplish with Link items: https://isaw.nyu.edu/exhibitions/current
This content item needs to be able to appear as part of the navigation tree, and it needs to be a link, because I'm going to change what it points to at least twice a year. Since I'm always going to be linking it to content within our site, it would make sense to have the option of browsing the site contents. Selecting the item internally should allow for dynamic pointing, preventing link breakage when/if the content item is moved to a new folder later. The current method of typing out the URL by hand leaves the possibility of breaking that link if the content item gets moved.

**Comment by cewing** [comment]
We should use Products.RedirectionTool for this.

**Comment by cguardia** [comment]
Added redirection tool and upgrade step to policy. Installed on staging.

**Comment by k2soule** [comment]
I see the new Aliases option now on staging. I'll go try it out.

**Comment by k2soule** [comment]
Unfortunately, this Alias feature isn't solving the issue. See my comment from October 28th; what we need is the functionality of a Link item that can sit in a particular folder - and appear in the nav bar for that folder - which links directly to an item elsewhere on the site. The example is the "Location and Hours" page in Exhibitions. We need to be able to have an item of that name appear in the nav section for each separate show, which links directly back to a single page at the top level of Exhibitions that actually contains the Location and Hours information (so that it only has to be updated once, in one place). An alias isn't a content item, from what I can tell, and therefore can't appear in the nav.

**Comment by skleinfeldt** [comment]
Hmmm, I may have completely misunderstood the problem, sorry. @k2soule is the problem just that it is tedious to create a Link content item that points to an internal page because you have to type out (or copy-paste) the internal URL? I'm afraid that's just how the Link content items work, nothing is broken - they are generally used for external links so this wasn't a common use case.

That would be a nice feature to add to Link items, but it may be a bit of work. Someone else should comment on that.

BTW as far as I know a Link won't be broken if the content item gets moved, due to Plone's automatic redirection. Try that.

**Comment by alecpm** [comment]
If using Link content is a problem because you don't want to have to copy/paste the target url (Plone will handle redirects due to renaming/moving content automatically as @skleinfeldt says), then there may be an add-on that allows using a reference field for the same purpose, it's quite old though and might need updates:

https://pypi.python.org/pypi/vs.alias

There's also a much more complicated add-on that's somewhat more recently maintained, but intended as a full ATLink replacement:

https://pypi.python.org/pypi/redturtle.smartlink/1.2.1

Both would require some testing, and probably only make sense if pasting internal urls into the normal Link url field poses an issue.

**Comment by cguardia** [comment]
@k2soule or @paregorios what do you want me to do here?

**Comment by paregorios** [comment]
@cguardia I will take this ticket temporarily so that I can discuss next steps with @k2soule

**Comment by k2soule** [comment]
Sally and Alec have hit upon my top concern - that a link item pointing to
an internal page by explicit URL would be broken if the target were later
moved.  Since you're both quite convinced that plone can handle this
circumstance, I'm ready to let this issue go without trying to implement
any additional add-ons.

Separately, I think that the redirect capability you've added here with
Products.RedirectionTool is going to be handy for it's own reasons - so
thank you for that!
