### ISSUE TITLE
owners and Editors cannot upload a file to a folder

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#63]
When a user with [can edit, can add, can view] tries to add a file to the /guide/forms folder, they get an infinite loop error in their web browser, which appears to be attempting a shibboleth authorization (though they are already logged in). We checked in Chrome, Safari, and Firefox on the Mac.

**Comment by paregorios** [comment]
@k2soule does this happen to you (i.e., an admin), or just to those with the permissions you outline above?

**Comment by k2soule** [comment]
This does not happen to me; it only seems to affect non-site-admins.
Also, I should note that Marc is having similar trouble uploading files in other locations, such as CVs for faculty.

**Comment by cguardia** [comment]
Is there a user account I can use to try this out?

**Comment by cguardia** [comment]
I was thrown off the scent by the shibboleth challenge.

The problem seems to be that the editor role does not have the "modify portal content" permission (this is set in the workflow). Editor role in plone has this permission by default. "Can edit" means that the editor role is locally assigned to the group, but since the role doesn't have the right permissions, this happens.

**Comment by k2soule** [comment]
Sounds like the editor role needs to have its "modify portal content" permission restored to the default setting. How do we go about doing that, and what are the possible side-effects (if any)?

**Comment by skleinfeldt** [comment]
@cguardia did you fix this or just diagnose? If this is your custom workflow it seems like it should probably be fixed in code and then an upgrade step run. I think that might take a while because it has to update stuff on all the relevant site content, so maybe one of the clients should be taken out of the load balancing rotation to work on that??? But I'm really out of my depth here, @cguardia should give the correct answer...

**Comment by k2soule** [comment]
An additional observation that I should tack on here, and remind myself to test after the fix is applied:
I'm noticing that content editors are unable to see the "grab handles" on items in Contents view; so they are unable to change the order in which items appear.

**Comment by cguardia** [comment]
Just diagnosis. You are right it will take some time. I can fix that tonight, when the re-indexing won't bother anyone. I don't think there will be side effects, other than all users with that role will have permission to edit content.

One thing that I found during these tests is that if you have any users with "can add" permission, but not "can edit", they won't be able to add files or images.

**Comment by paregorios** [comment]
Please let's hold off on implementation of this on production. I'm not
confident that we have fully understood workflow desires across the entire
site yet, and one-off changes may introduce more confusion. I'll try to
have more comprehensive feedback by Monday sometime.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cguardia** [comment]
Ok.

**Comment by paregorios** [comment]
A few questions as I'm building tests on staging:

1. Where can I go in the repos to look at the code for the "modify portal content" permission and its relationship to the "editor" role? I'd like to see if we have history on when it was changed so we can try to figure out *why* it was changed.
1.  I'd like some clarification on @cguardia' comment above "if you have any users with "can add" permission, but not "can edit", they won't be able to add files or images"; namely, is this a description of the current state of affairs, or a description of what we should expect after the change is made? If the latter, then we have a bigger problem.

**Comment by cguardia** [comment]
1. Default workflow definition is here. Look for entries for "modify portal content" for each state: 

https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_standard_workflow/definition.xml

Some parts of the site use the intranet workflow locally:

https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_intranet_workflow/definition.xml

2. My comment referred to the current state of affairs.

**Comment by paregorios** [comment]
I've looked at the code @cguardia pointed to (thanks!) and here's what I think I see:

### for the "isaw standard" workflow:

* in "draft" the "Editor" (can edit) role has the "modify portal content" permission [line 25](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_standard_workflow/definition.xml#L25)
* but not in ["pending"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_standard_workflow/definition.xml#L54) nor in ["published"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_standard_workflow/definition.xml#L67) 

The change removing "Editor" from the "pending" state in the  "isaw standard" workflow policy was introduced by @alecpm on 28 August @feb9cf9e4db29bfbe899a615463979b82e1c0d4b, clearly as part of changes stemming from #48. Note in particular [his comments here](https://github.com/isawnyu/isaw.web/issues/48#issuecomment-135901460).

### for the "isaw reviewer" workflow:

NB:  The "isaw reviewer" workflow appears to be applied via code to ["event" items](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows.xml#L27) and ["news" items](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows.xml#L32) ... see also #51):

The difference is that the "Editor" role gets "modify portal content" in both ["draft"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_reviewer_workflow/definition.xml#L24) and ["pending"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_reviewer_workflow/definition.xml#L58).

### for the "isaw intranet" workflow:

NB: This workflow is [applied locally to /guide via placeful workflow](https://isaw.nyu.edu/guide/placeful_workflow_configuration).

Like the "isaw reviewer" workflow, the "Editor" role gets "modify portal content" in both ["draft"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_intranet_workflow/definition.xml#L23) and ["pending"](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_intranet_workflow/definition.xml#L83).

### Discussion:

Since the "isaw intranet" workflow is [set for the /guide folder itself and for its children](https://isaw.nyu.edu/guide/placeful_workflow_configuration), and since the "isaw intranet workflow" provides "Editor" with "modify portal content", I'm puzzled as to how the diagnosis articulated by @cguardia can be causing the problem articulated in the title of this issue. Could it simply be the case for /guide/forms that we haven't given the right people the right permissions via @@sharing? But it's quite possible that there's still some piece of the equation here that I haven't grasped.

I note, moreover, that we have reports of the same (or similar) permissions failures (perhaps only in appearance?) when trying to upload files or images in other contexts:

* inside profiles ([see @k2soule's comment above](https://github.com/isawnyu/isaw.web/issues/63#issuecomment-162025325))
* inside /news and /events (see issue #51)

### Next steps: Clarity through testing. 

I hope that we can achieve a little more clarity after I expand [tests on staging](https://docs.google.com/a/nyu.edu/document/d/1b3QBa7OPyNYBYfyV1HDfanp9xER5Uh0snz8hFXhYz-s/edit?usp=sharing) to make sure we're covering all these bases. It's my impression, for example, that my tests already cover the case of uploading files inside user profiles, and that thatproblem was just fixed via #71.

I will append a new comment here when I get to the point where I'm ready to ask new questions (but comments prompted by the above are welcome at any time).

**Comment by skleinfeldt** [comment]
Although I'm sure these problems are fixable (whatever they are), given the time you are spending on this I am reminded of a talk Joel Burton gave at the D.C. Plone Conference, about how even though Plone lets you create whatever custom workflow you think you want, it is not always advisable to do so. (inefficiencies, bottlenecks, painting yourself into a corner...) Just have to ask - have you considered sticking with standard workflows and trusting people to do the right thing?

**Comment by paregorios** [comment]
Narrowing this ticket and queuing it up for action. Here's a restatement of the specific problem we are trying to solve with this ticket:

The following kinds of users need to be able to upload images in a folder, but presently get a permissions error if they try:

* owner of the folder
* user with "Can Add" and "Can Edit" applied via the folder sharing tab

@cguardia has diagnosed the problem (see preceding); I'm ready to see this addressed and deployed to staging so we can test it there.

**Comment by paregorios** [comment]
Renaming ticket accordingly

**Comment by paregorios** [comment]
Request this ticket be applied not only to folders governed by the "isaw standard" workflow, but also folders governed by the "isaw internal" workflow. Tests reveal the same behaviors in both contexts.

**Comment by cewing** [comment]
@paregorios, @cguardia this issue has landed on my plate to implement, and I want to make sure that my understanding matches reality, given the lengthy discussion above.

Here's what I am reading as the expected actions for this ticket:

* Add the `Modify portal content` permission for the `Editor` role in the `pending` state in the `isaw intranet workflow`.  

I am unclear about the reference by @paregorios [above](https://github.com/isawnyu/isaw.web/issues/63#issuecomment-164062834) to the `isaw internal` workflow.  Even assuming that what is meant is `isaw intranet workflow`, the `Modify portal content` permission is assigned to the `Editor` role in the `pending` state for that workflow.  Have I missed another permission or state or role reference in the discussion that would help me to understand exactly what to change here?

@paregorios you are, I assume, okay with the idea that @alecpm's changes in #48 removing the ability of editors to edit content in the `pending` state will be reversed by this change?

**Comment by cewing** [comment]
@paregorios, having reviewed other issues assigned to me I am officially confused.  The apparent request here to add `Modify portal contents` to the `Editor`  role on the `isaw intranet workflow` here on this issue appears to directly contradict the request made in #105 which asks to remove the same permission from the `Editor` role on the `isaw standard workflow` in order to make the behavior of these two workflows consistent.

**Comment by paregorios** [comment]
@cewing I think the problem here may be that we are trying to achieve two things that Plone won't let us split because they're bound to the same permission (i.e., "modify portal contents"). Or maybe we're not explaining ourselves correctly. Here's what we want (#103 and #63 combined; #105 addresses an edge case):

* For content items that are governed by workflow (pages, folders, etc etc), owners and "can edit(ors)" should __not__ be able to edit, checkin, or delete items in "pending" or "published" (external or internal) state. 

* For content items NOT subject to workflow (images, files), folder owners and "can add(itors)" __should be able__ to upload.

The rationale being: if only "can review(ers)" can publish, why should non-reviewers be able to modify published content without subsequent review? That's why we added the checkin/checkout procedure in the first place. But since Plone no longer thinks images and files should be under the control of workflow, why should the default be that only our reviewers or admins can add them? 

I am not well versed in the minutiae of the plone permissions model, but what I outline above is the behavior we are seeking. If the Plone gods are bent on our driving us mad before they destroy us, and these two bullets are mutually incompatible, then I am prepared under protest to give up the quest for blocking live modification in order to get back the ability to add images and files, without which we are sorely handicapped in our curation process. 

But perhaps we should talk about this to ensure we're on the same wavelength?

**Comment by cewing** [comment]
We've discovered the culprit here.  

Although files and images do not have a workflow that controls them, they do have access controls that check permissions to determine what can be done with them.  Since their own workflow cannot provide information about what permissions belong to which users, they fall back to inheriting their permissions from the containers in which they are located.

What this means in practice is that although with the 'owner' or 'editor' role has the right permission to add a new object, viewing the form that is used to fill out information needed by the object is controlled by  the 'Modify portal content' permission.  Since there is no workflow on images and files, this permission is inherited from the 'published' folder in which the image/file is being created and those roles are not allowed that permission in those states.

The solution to this problem is to set a workflow on the file and image objects.  In order to preserve the expectation that all image and file objects are visible to anyone, the correct workflow is the built-in Plone one-state workflow.  Assigning this to all images and files solves the problem without needing to allow owners and editors to also have the ability to modify the folder in which the new image/file is located.

I've added this workflow binding to the `isaw.policy` package profile and set up an upgrade step that will execute the needed changes.  This will be applied when the upgrade is run.

**Comment by paregorios** [comment]
My associated tests are now passing on staging, but it looks to me like the branch of isaw.policy deployed there is master. So I'm puzzled why it should be working now, even though the associated changes have not been merged to isaw.policy:master yet.

**Comment by cewing** [comment]
@paregorios It's because I manually made the change on staging yesterday to confirm that it would work.

**Comment by paregorios** [comment]
OK, cool. Thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cewing** [comment]
This should now be 100% fixed (the PR above merely ensures that these changes are official, and happen on production as well)

**Comment by cewing** [comment]
@paregorios this is deployed and ready to test.  Your selenium test suite covers this issue well, and you should expect all tests related to it to pass.

**Comment by paregorios** [comment]
@cewing deployed to staging or to production? I'm hoping just staging at this point...

**Comment by cewing** [comment]
Staging, I believe.  I don't think we deploy to production without your review and go-ahead.

**Comment by skleinfeldt** [comment]
Yes, staging.

**Comment by skleinfeldt** [comment]
Yes, staging.

**Comment by paregorios** [comment]
All tests passing. Closing as resolved.
