### ISSUE TITLE
maddening amounts of internal whitespace at bottom of rich text boxes in edit view

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#88]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Thursday Jun 04, 2015 at 20:38 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/33_

----

We've been living with this for a long time on production; I was hoping it would magically go away with upgrade and new theme, but it's still very much with us. Wouldn't be so bad if the body richtext box were the last field on the edit form (it's not always), and if the save button was at the top of the form instead of the bottom. As it is, you sometimes have a marathon scroll. 

Behold:

![death-by-scroll1](https://cloud.githubusercontent.com/assets/263285/7993966/900224ec-0acf-11e5-85e2-4b9642265b68.jpg)

wait, wait, there's more:

![death-by-scroll2](https://cloud.githubusercontent.com/assets/263285/7993972/99b462a2-0acf-11e5-9581-84e2aec6d045.jpg)

And, no, there are not any blank lines following the line "etc. and so forth"

**Comment by paregorios** [comment]
<a href="https://github.com/cewing"><img src="https://avatars.githubusercontent.com/u/417109?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cewing](https://github.com/cewing)**
_Thursday Jun 04, 2015 at 20:58 GMT_

----

it is absurdly awesome.

**Comment by paregorios** [comment]
<a href="https://github.com/skleinfeldt"><img src="https://avatars.githubusercontent.com/u/1198463?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skleinfeldt](https://github.com/skleinfeldt)**
_Thursday Jun 04, 2015 at 23:13 GMT_

----

It's so absurdly maddeningly awesomely awful I don't know who to assign this to.

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Thursday Jul 09, 2015 at 20:28 GMT_

----

this may be a chrome bug

**Comment by paregorios** [comment]
<a href="https://github.com/k2soule"><img src="https://avatars.githubusercontent.com/u/7882896?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k2soule](https://github.com/k2soule)**
_Friday Sep 18, 2015 at 19:12 GMT_

----

not just chrome; I have observed this in Safari and Firefox as well

**Comment by paregorios** [comment]
<a href="https://github.com/k2soule"><img src="https://avatars.githubusercontent.com/u/7882896?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k2soule](https://github.com/k2soule)**
_Wednesday Sep 23, 2015 at 18:38 GMT_

----

Also, as Roger pointed out today, there is the problem of the editing window being located incorrectly in the browser window; such that the right side of the content is off-screen, and one has to scroll to the bottom of the page to get another scroll bar to move the editing window into view... Is this related? Or should it be a separate ticket?

**Comment by paregorios** [comment]
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [paregorios](https://github.com/paregorios)**
_Wednesday Sep 23, 2015 at 18:43 GMT_

----

I think it warrants a separate ticket, but with a cross reference link.

**Comment by cewing** [comment]
After quite a lot of mucking about, it turns out that there are a number of things at play here.

First, TinyMCE calculates the size of the editor window based on configuration at the time when the page loads.  It *might* be possible to add CSS rules to control this to some degree, but that seems inadvisable.  Instead, I think that using configuration settings to get what you want is the right way to go.

At the moment, the reason that the editor is showing so large is that it is set to allow "automatic resizing".  This means that the editor always shows everything that is in the window, but it also means that it is calculating the vertical size of the editor window on the fly, which is clearly not working great.  I suggest that we disable auto-resizing and instead allow users to re-size the editor window themselves.  We should also remove any specific size for the editor window, and allow it to render at an "appropriate" size on page load.  The "user resize" functionality uses cookies to remember the size a user set for a given editor and so it should allow users to get to the most comfortable size for themselves.

It turns out that the problems noted on the editor width ticket are related, I will paste more suggested settings there.

### Suggested Settings

on `/portal_tinymce/@@tinymce-controlpanel`

#### Layout Tab

- **Enable resizing the editor window**: select this
- **Enable auto resizing of the editor window**: unselect this
- **Editor width**: set to 100%
- **Editor height**: empty (no value should be set here)

**Comment by paregorios** [comment]
I've made these changes and all appears good on production. Closing as resolved.
