### ISSUE TITLE
match staging to production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#94]
I think in order for us to get to the bottom of exactly what's needed regarding several of the tickets (all the November milestone ones currently assigned to me for review), we need a check/refresh on staging so we can put content through its paces with confidence that we're working in an environment that's as much like production as possible.

Is it possible to:

 * verify that we're running the same code on staging as on production, and
 * replicate file and blog storage over from production to staging so that we have the latest content and database settings?

**Comment by alecpm** [comment]
I can confirm that staging and production are running revision c8a2ecc3eb974ea76ce75d4c56145703cc2a7806 of the buildout.  There are a couple manual edits on each server though.  Staging is using the ``staging`` branch of isaw.theme, where production is using ``master``; however, at present ``staging`` and ``master`` are identical.  Staging still has the ``isaw.events`` package in ``src/``, but it's not being included in the python path.  Staging is running development.cfg rather than production.cfg, but development.cfg just adds some debug tools and reduces the number of zope clients.

Beyond those minor configuration differences, the code on the servers appears to be identical (same revisions no local modifications).  I'll replicate the data to staging shortly.

**Comment by alecpm** [comment]
Staging data should now be identical to production.

**Comment by paregorios** [comment]
Great! Thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
I'm taking this ticket for review.

**Comment by paregorios** [comment]
Confirmed. Closing.
