### ISSUE TITLE
plone test users on staging do not stay logged in

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#99]
Steps to reproduce:

 * navigate to staging/portal_skins/plone_login/login_form
 * plone user ```foo``` logs in using form and gets expected login confirmation (and appropriate additional stuff in footer)
 * navigation away from this page to any other page (either via link or by manipulating url in browser location bar) seems to lose the login information. No action menus appear and footer drops logged-in info.

This is a blocker for the workflow-related issues in the December milestone that are assigned to me for review.

**Comment by skleinfeldt** [comment]
Contact me for info on how to log in as `foo`.

**Comment by alecpm** [comment]
@skleinfeldt could you skype me the credentials for foo?  I'm not seeing the issue with my own ZMI account.

**Comment by alecpm** [comment]
Is this happening with your ZMI root account (paregorios or paregorian) or an account defined within Plone?

**Comment by paregorios** [comment]
Only with an account defined within Plone (for which @skleinfeldt has the
credentials). It is not happening with my ZMI root account. The same
Plone-defined account ("foo") works fine on production.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
The issue was that the cookie based session auth settings in acl_users were setup with a hardcoded domain for the cookie (.isaw.nyu.edu) which wasn't compatible with the actual domain for the staging site.  I cleared that property (here http://isaw4-dev.atlantides.org/acl_users/session/manage_propertiesForm), so that the cookie is set for the current hostname.  This issue will recur whenever the production is copied to staging, unless this field is again blanked out.  It may make sense to blank the field in production if you don't need the authentication cookie to be served to multiple .isaw.nyu.edu subdomains for all users.

**Comment by paregorios** [comment]
Thanks, just saw this was assigned to me. I didn't get an email notification from github! Will test asap.
